//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.NET06.TwitterListener.Data {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class DataSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static DataSettings defaultInstance = ((DataSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DataSettings())));
        
        public static DataSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Server=.\\SQLExpress;Database=ListenerManager;Trusted_Connection=True;MultipleActi" +
            "veResultSets=true")]
        public string ListenerManagerConnection_old {
            get {
                return ((string)(this["ListenerManagerConnection_old"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLExpress;Initial Catalog=ListenerManager;Integrated Security=True" +
            "")]
        public string ListenerManagerConnection_old1 {
            get {
                return ((string)(this["ListenerManagerConnection_old1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=tcp:twitterlistenermanagerdbserver.database.windows.net,1433;Initial " +
            "Catalog=TwitterListenerManager_db;User Id=listenermanageradmin@twitterlistenerma" +
            "nagerdbserver;Password=q3bG58.DP")]
        public string ListenerManagerConnection {
            get {
                return ((string)(this["ListenerManagerConnection"]));
            }
        }
    }
}
